[#46] 팔로우 취소
f-lab-edu/instagram-social-media pull request #47
Opened 2020-12-05 09:25 UTC by choitaehoon

- 팔로우 delete 구현

2020-12-06 12:17 UTC, f-lab-dev commented on src/main/java/com/social/instagram/repository/FollowRepository.java
> +    @Transactional(rollbackFor = Exception.class)
이거는 `SQLException`을 염두에 두신건가요?

2020-12-07 04:18 UTC, choitaehoon commented on src/main/java/com/social/instagram/repository/FollowRepository.java
> +    @Transactional(rollbackFor = Exception.class)
`SQLException`을 염두했습니다. `@Transactional`에 checked Exception은 Rollback 대상이 아닌데 만일 `SQLException`이 발생하게 되면 데이터 정합성 이슈가 발생할 가능성이 존재하여 선언했습니다

2020-12-07 14:11 UTC, f-lab-dev commented on src/main/java/com/social/instagram/repository/FollowRepository.java
> +    @Transactional(rollbackFor = Exception.class)
그러면 이럴땐 `SQLException`이 외부로 전파될텐데 이거는 다른 예외 타입으로 감싸서 던지는게 낫지 않을까요?

2020-12-09 12:44 UTC, f-lab-dev commented on src/main/java/com/social/instagram/exception/FollowNotDeleteException.java
> +public class FollowNotDeleteException extends SQLException {
1. 조금 더 범용적으로 `FollowOperationFailedException` 정도로 해주면 어떨까요?
2. `SQLException`은 checked exception인데 이것을 상속받으신 이유가 무엇인가요?

2020-12-10 05:16 UTC, choitaehoon commented on src/main/java/com/social/instagram/exception/FollowNotDeleteException.java
> +public class FollowNotDeleteException extends SQLException {
1. ` FollowNotDeleteException`은 팔로우 삭제가 되지 않은 에러라고 해석할 수 있고 `FollowOperationFailedException`
은 팔로우 기능이 실패한 에러라고 볼 수 있는데 둘 중에 비교하면 팔로우 기능이 실패한 에러가 더 자연스럽네요. 좋은 것 같습니다
2. unchecked exception 으로 감싸야 됐었는데 잘못했네요. 데이터 엑세스 기술의 종류와 상관없이 일관된 예외가 발생 할 수 있도록 `DataAccessException` 구현하겠습니다.

2020-12-10 13:12 UTC, f-lab-dev commented on src/main/java/com/social/instagram/exception/FollowOperationFailedException.java
> +public class FollowOperationFailedException extends DataAccessException {
`Follow`에 실패한 이유가 꼭 데이터 접근과 관련된 상황만 있을까요? 부모 클래스도 적절하게 선택해주시는게 좋을 것 같습니다~

2020-12-12 03:44 UTC, choitaehoon commented on src/main/java/com/social/instagram/exception/FollowOperationFailedException.java
> +public class FollowOperationFailedException extends DataAccessException {
아 그렇군요. 그렇다면 그보다 상위클래스인 `Exception`으로 잡는건 어떨까요?

2020-12-12 16:53 UTC, f-lab-dev commented on src/main/java/com/social/instagram/exception/FollowOperationFailedException.java
> +public class FollowOperationFailedException extends DataAccessException {
그건 checked exception 아닌가요??

2020-12-12 16:53 UTC, f-lab-dev requested changes
부모 예외쪽만 한번 확인해주세요~

2020-12-13 08:51 UTC, choitaehoon commented on src/main/java/com/social/instagram/repository/FollowRepository.java
> +    @Transactional(rollbackFor = Exception.class)
다시 한번 생각을 해보니 `rollbackFor`은 롤백의 대상여부를 결정하는데 여기에 unchecked exception인 다른 예외 타입으로 감싸서 던지면 checked exception은 롤백이 안되지 않을까요?

2020-12-13 14:38 UTC, f-lab-dev commented on src/main/java/com/social/instagram/repository/FollowRepository.java
> +    @Transactional(rollbackFor = Exception.class)
네 checked exception은 애초에 외부에 전파하지 않아도 되는것이지 않을까요?

2020-12-14 09:38 UTC, choitaehoon commented on src/main/java/com/social/instagram/repository/FollowRepository.java
> +    @Transactional(rollbackFor = Exception.class)
저도 `checked exception`을 외부에 전파하지 않고 `unchecked exception`으로 감싸서 던지는게 낫다고 봅니다. 그렇다면 저희 상황에서는 `rollbackFor`의 대상여부를 `checked exception`으로 던질 수 밖에 없는 상황이고 `unchecked exception`으로 감싸서 던져야 하는 상황이라면 스프링에서 추상화 시킨 `PlatformTransactionManager`를 이용하여 `SQLException`이 발생하면 rollback 시키고 `unchecked exception`으로 감싸서 보내면 어떨까요?

2020-12-16 02:46 UTC, f-lab-dev approved these changes

2020-12-22 07:18 UTC, merged