[#55] 피드 댓글 작성
f-lab-edu/instagram-social-media pull request #56
Opened 2020-12-23 13:11 UTC by choitaehoon

- 피드 댓글 구현
- 댓글 requestDto 생성

2020-12-24 04:52 UTC, f-lab-dev commented on src/main/java/com/social/instagram/controller/CommentController.java
> +    public ResponseEntity<Void> comment(@RequestBody CommentRequestDto commentRequestDto) {
이거는 `@ResponseStatus(HttpStatus.CREATED)` 를 붙여주면 `void`를 리턴해줘도 되겠네요~
그럼 코드가 좀 더 간결해질 것 같습니다

2020-12-24 15:29 UTC, choitaehoon commented on src/main/java/com/social/instagram/controller/CommentController.java
> +    public ResponseEntity<Void> comment(@RequestBody CommentRequestDto commentRequestDto) {
좋은 리뷰 감사드립니다 &#128578; 
 `ResponseStatus`의 `reason`을 설정할 때 spring은 `HttpServletResponse`의 `sendError()`를 호출하게 되는데 클라이언트에 HTML 오류 페이지를 전송하므로 REST에 적합하지 않는걸 파악해 추후에 `reason`을 조심히 사용하겠습니다

2020-12-25 03:31 UTC, f-lab-dev approved these changes

2020-12-26 03:04 UTC, f-lab-dev commented on src/main/java/com/social/instagram/dto/request/CommentRequestDto.java
> +                .orElseThrow(CommentValidatedFailException::new);
null check는 이거말고 다른 방식들도 있을텐데 이렇게 검사하신 이유가 있으실까요?

2020-12-26 03:04 UTC, f-lab-dev commented on src/main/java/com/social/instagram/dto/request/CommentRequestDto.java
> +        static final int POST_MIN = 0;
이거는 여기서만 쓰일거라면 굳이 클래스로까지 분리할 필요가 있을까 싶네요~

2020-12-26 03:04 UTC, f-lab-dev commented on src/main/java/com/social/instagram/controller/CommentController.java
> +        CommentRequestDto.validate(commentRequestDto, sessionService.getUserId());
이런 로그인한 유저아이디는 `Controller`에서 `@ RequestBody` 같이 어노테이션이 달린 인자로 받을 수 있게 처리해줄 수 있는데 그런것들을 해보면 어떨까요?

2020-12-26 08:51 UTC, choitaehoon commented on src/main/java/com/social/instagram/dto/request/CommentRequestDto.java
> +                .orElseThrow(CommentValidatedFailException::new);
최신 커밋에 대한 리뷰 반영이 안된 것 같은데 확인 부탁드립니다 🙂

2020-12-26 08:51 UTC, choitaehoon commented on src/main/java/com/social/instagram/dto/request/CommentRequestDto.java
> +        static final int POST_MIN = 0;
https://github.com/f-lab-edu/instagram-social-media/pull/56#discussion_r548960876

2020-12-26 08:51 UTC, choitaehoon commented on src/main/java/com/social/instagram/controller/CommentController.java
> +        CommentRequestDto.validate(commentRequestDto, sessionService.getUserId());
https://github.com/f-lab-edu/instagram-social-media/pull/56#discussion_r548960876

2020-12-27 16:42 UTC, f-lab-dev approved these changes

2020-12-27 16:42 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    public void comment_Fail_When_No_PostIdOrUserId() {
여기는 카멜케이스 지켜주세요~

2020-12-28 07:42 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    public void commentSuccessSave() {
junit에 보면 테스트의 이름을 지어줄 수 있는 옵션이 있습니다. 그러면 한글로 시나리오를 표현할 수도 있는데 그것도 고려해주세요~

2020-12-28 07:42 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +        assertThat(sessionService.getUserId(), equalTo(USER_ID));
`given(sessionService.getUserId()).willReturn(USER_ID);` 을 통해 `USER_ID`를 리턴하게 해놨으니 이거는 무조건 true가 나올 것 같네요

이 라인은 메소드의 스펙에 대한 테스트라고 볼 수 있을까요?

2020-12-28 08:54 UTC, choitaehoon commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    public void commentSuccessSave() {
`@DisplayName`도 고려했지만 메소드 이름만으로 충분히 의미를 전달해줄 수 있을거라 생각해서 적지 않았습니다. 한글로 시나리오를 표현하면 클래스나 전체 패키지의 테스트코드를 돌릴 때 한글로 되어 있어 여러 테스트를 한 눈에 파악하기 쉽다는 장점으로 `DisplayName`을 고려하라는 의미이실까요? :)

2020-12-28 09:03 UTC, choitaehoon commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +        assertThat(sessionService.getUserId(), equalTo(USER_ID));
`assertThat`으로 값을 검증하는 게 아니라 `verify`로 행위를 검증하는게 더 적합하네요. 감사합니다 :)

2020-12-29 02:03 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    public void commentSuccessSave() {
네 맞습니다~ 메소드 이름으로 `정해진 범위의 숫자가 아닌 값이 입력될 경우 ~~예외를 던진다` 등의 복잡한 테스트 케이스를 충분히 가독성높게 전달할 수 있을까요?
또한 유지보수하는 사람이 한국인이냐, 외국인이 섞여있냐도 고려해야겠네요. 항상 이 테스트를 읽을 사람을 최대한 배려해주는게 좋습니다

2020-12-30 01:50 UTC, f-lab-dev requested changes

2020-12-30 01:50 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    @DisplayName("댓글을 데이터베이스에 저장한다")
설명을 보면 `~~한다`로 되어있는데` 어떤 상황에 저장에 성공하는 상황인지 좀 더 케이스가 명확했으면 좋겠습니다

2021-01-02 07:33 UTC, choitaehoon commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    @DisplayName("댓글을 데이터베이스에 저장한다")
감사합니다 😊  시나리오를 구체적으로 적겠습니다!

2021-01-02 13:09 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
> +    @DisplayName("레디스에 ID를 가져오고 댓글DTO를 도메인으로 변경 후 댓글 저장에 성공한다")
테스트 대상 클래스는 `CommentServiceTest` 입니다. 이 클래스는 레디스에 의존적일까요?
또한 여깄는 설명은 테스트의 시나리오에 대해 설명해주는게 좋습니다.

이 테스트 코드를 읽어보면 `현재 로그인된 유저의 ID로 댓글을 저장소에 저장한다` 정도로 풀어볼 수 있겠네요

2021-01-05 02:41 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
>          given(sessionService.getUserId()).willReturn(USER_ID);
1. 이제 리팩토링할거리도 보일 것 같네요~ `로그인된 유저의 아이디를 가져온다` 라는 행위에서 세션은 구체적인걸까요 추상적인걸까요?
2. 제가 제시해드린 이름을 그대로 적용하셨는데 더 좋은 이름이 있는지도 고민해보셨는지 궁금합니다

2021-01-05 10:47 UTC, choitaehoon commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
>          given(sessionService.getUserId()).willReturn(USER_ID);
1. `로그인된 유저의 아이디를 가져온다`라는 행위에서 세션은 추상적입니다. `HttpSession`의 `getAttribute(name)`으로 호출하면 현재 레디스로 세션을 이용하고 있으니까 `HttpSessionAdapter`에서 `RedisSessionRepository`를 이용하여 가져옵니다
2. `유저 ID를 기반으로 댓글을 데이터베이스에 저장한다` 와 `댓글을 데이터베이스에 저장된다` 등 댓글 저장에 대한 시나리오 문장이 있는데 생각해보면 `현재`라는 키워드를 빼고 `로그인된 유저 ID로 작성한 댓글을 저장소에 저장한다`가 더 좋은 이름 같네요~

2021-01-06 08:23 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
>          given(sessionService.getUserId()).willReturn(USER_ID);
그럼 클래스도 `sessionService`에 의존하는게 아니라 `loginService` 혹은 `authService`에 의존해야하는게 아닐까요?

2021-01-07 05:37 UTC, choitaehoon commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
>          given(sessionService.getUserId()).willReturn(USER_ID);
현재 `sessionService`안에서 `HttpSession`을 감싸 세션 ID를 등록하고 가져오는 역할을 하고 있습니다. 그러면 `loginService`에서도 이러한 역할을 한다면 동일하지 않을까요~?

2021-01-07 06:32 UTC, f-lab-dev commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
>          given(sessionService.getUserId()).willReturn(USER_ID);
구현 내용은 유사하지만 댓글을 쓸 때 `로그인 관련 기능에 의존한다` 와 `세션 관련 기능에 의존한다` 의미의 차이로 읽힐 수 있을 것 같네요.

현재 댓글관련 서비스는 로그인을 해야만 사용할 수 있으므로 `로그인 관련 기능에 의존한다`가 더 어울리지 않을까요?

2021-01-08 04:40 UTC, choitaehoon commented on src/test/java/com/social/instagram/service/CommentServiceTest.java
>          given(sessionService.getUserId()).willReturn(USER_ID);
로그인이 세션보다 더 와닿게 들리네요. 로그인 이외에 기능이 추가 될 경우 `sessionService`은 어떤 역할을 하는지 명확하지 않을 수도 있겠네요.

2021-01-08 05:53 UTC, f-lab-dev approved these changes

2021-01-08 06:48 UTC, merged